const { Client } = require('./node_modules/pg');
const client = new Client({
  host: 'kodama.proxy.rlwy.net', port: 55551,
  user: 'postgres', password: 'yBtFmogbIuHGfNhHFhzrmlhANWfgrzxC',
  database: 'railway', ssl: { rejectUnauthorized: false }
});

const USER_ID = 'a4ede2f8-b3b1-4158-816f-e7503dab81a4';

const memories = [
  {
    key: 're_sms_double_whammy',
    value: 'SMS carrier bypass system: Two-text method. Text 1 (goal = get ANY reply): "Hey, this is [name]. I just drove by your place at [address] and something seemed off. Is everything alright?" — embedding the address makes every text unique so carriers cannot flag as spam. A reply permanently overrides spam filters for that thread. Text 2 (send AFTER any reply): "Hey, I was just seeing if you\'re interested in selling your house for cash. I\'m looking to buy a couple more properties in the area." BONUS: Using a woman\'s name increases reply rate 20%. Google Voice free: max 5 texts/hour per account — use 6 accounts simultaneously = 30/hour = 300/day free. Paid via XLeads Ninja Mode: $0.0087/text ($8.70 per 1,000). Opt-out: "Stop owning your house" counts as legal opt-out language.'
  },
  {
    key: 're_market_selection_criteria',
    value: 'Market qualifies for wholesaling if BOTH criteria met: (1) County population 100,000+ (ensures economy + buyer demand). (2) County median home price under $500,000 (sellers accept deeper % discounts on lower-priced homes). 300+ US counties qualify. Memphis (Shelby County): ~929K population, median ~$175K = A-tier ideal. Best underrated virtual markets: Oklahoma City OK, Dayton OH (Montgomery County), Clarksville TN, Chattanooga TN, Knoxville TN, Toledo OH (probates free online), Detroit MI (avg house under $70K), Louisville KY, Gastonia NC (Gaston County), Fort Wayne IN, Little Rock AR, Fresno CA (only viable CA virtual market), Brevard County FL. AVOID: NYC, Miami, Chicago city, Los Angeles.'
  },
  {
    key: 're_email_offer_generator',
    value: 'Free mass email outreach system: Google Sheets + Gmail Mail Merge. Formula: offer = XLeads AVM × 0.83 (83% of AVM). Gmail blocks "address" and "offer" as column headers — rename to "addy" and "off" to bypass filter. Subject: "Your cash offer is here." Template: "Hey {{FirstName}}, I\'m offering you ${{OFF}} for the house at {{ADDY}}. We can close in as little as 7 days. Cash, no repairs, no commissions, no stress. You sell as-is and I cover closing costs. This offer is only good for 7 days. Call me at [number] whenever you\'re free." Scale: 30,000 emails/month = consistent deal flow. Cost = $0. Benchmark: 60,000 emails ≈ 1 deal. Use Zach\'s mail merge Google Sheet template (in course).'
  },
  {
    key: 're_government_list_tactics',
    value: 'Government offices initially refuse lists. 5 bypass tactics: (1) Play dumb — "What happens when someone dies and has a house?" Let them explain. Ask "What is that court filing called?" They say "probate." Ask "How do I access those records?" (2) Request court dockets instead — legally must be posted; all probates/foreclosures/liens appear on dockets. (3) FOIA as leverage: "I would hate to file a FOIA request — that means you are withholding public government information, which is a federal law violation." Works on utility departments. (4) Newspaper threat for water shutoffs: "So nobody in this city has to pay their water bill because you don\'t keep records?" (5) School project framing: "My daughter is doing a research project and I\'m helping." Resistance levels (1=easy): Pre-foreclosures=2, Divorce=3, Liens=3, Arrest records=4, Code violations=5-7, Probates=6, Water shutoffs=8. ChatGPT workflow: Screenshot court docket → upload → "Organize into spreadsheet, only include entries with real property." Probate step-by-step: county clerk → search "Probate" → filter to property descriptions → note address → county property appraiser → confirm → CyberBackgroundChecks.com → find heir → call heir. Pre-foreclosure: Lis pendens filed at ~month 4 (120 days). TEXT pre-foreclosures — never call (over-called by banks).'
  },
  {
    key: 're_xleads_filter_recipe',
    value: 'Exact XLeads filter recipe for Memphis (default campaign settings): INCLUDE: Vacant properties (USPS marks vacant after 2-3 weeks no mail pickup) + High equity 40%+ minimum (60% preferred). EXCLUDE: Active MLS listings + Active investor owned. Additional: Property value max ~$220K (slightly above Memphis $175K median), Single family only, Owner type: individuals and trusts only, Ownership duration 3+ years (5+ preferred). Key distinctions: Absentee owner = landlord (owner lives elsewhere). Vacant = USPS confirms no mail pickup. Zombie property = pre-foreclosure THAT IS ALSO vacant (highest motivation). Tired investor = owner 25+ years. XLeads basic: 15K skip traces/month. XLeads X plan: 60K skip traces/month. Vacant + high equity + no active investors + no MLS = highest motivation pool with least competition.'
  },
  {
    key: 're_arv_comping_rules',
    value: 'ARV comping rules (apply in this order): (1) Square footage: +/- 200 sqft only. (2) Location: 0.25-mile radius max, same subdivision, never cross major streets, same school district. (3) Same bedroom/bathroom count. (4) Year built: +/- 10 years. (5) Sale date: last 3 months only — not 6 or 12. (6) Single family only. Calculation: average $/sqft of 4-5 comps × subject property sqft = ARV. Best comp is the property itself (prior sale + time inflation). Zillow = directional compass only (off 10-20%, usually high). "Cheat a little" rule: Next-door same street sold within 2-3 weeks = acceptable even with slight bed/bath difference. NON-DISCLOSURE STATES (cannot see sold prices): Idaho, Kansas, Missouri, Mississippi, Louisiana, Wyoming, Utah, Texas, North Dakota, New Mexico, Montana — need MLS access ($35-64/month + license) or XLeads subscription. PROPERTY APPRAISER HACK: Check permit history for actual roof age — if built 2002 and no roof permit, roof is 20+ years old ($20-30K value reduction). Never ask seller about roof age — they lie. School district: $20-30K price difference possible within same street.'
  },
  {
    key: 're_qualifying_sellers_mctp_deep',
    value: 'MCTP framework deep dive with specific language: ODN AVATAR = Off Market, Direct-to-seller, that Needs to sell (never "wants to sell"). M=MOTIVATION (ask first): "What is your reason for selling the house?" Then ZIP your lip. Get the full human story. Real estate is a symptom of human problems. C=CONDITION (open-ended): "Tell me about the current state of the house. What\'s going on with it?" NOT a checklist. If they say "it\'s great" = no trust yet. More they talk bad = more they want out. T=TIMELINE (most important): "What is your ideal time frame to sell?" SECRET QUESTION to unlock true timeline: "If I was able to buy your house today, where would you and your family be relocating to?" ZIP LIP. Their first response = truth. No answer = 180+ days out. "My aunt\'s in Charlotte by end of the month" = hot lead (<30 days). Categories: <30 days = drop everything; 30-90 = full focus; 90-180 = monthly check-in; 180+ = quarterly nurture. P=PRICE (always last): NEVER say "How much do you want?" Use: "What do you need to get out from under this property?" If price is high: "How did you come up with that number?" Shut up. Then: "I haven\'t found anything sold above $X fully fixed up. Are you planning to fix it up and list with a realtor?" 80/20 rule: Seller speaks 80% of the time.'
  },
  {
    key: 're_cash_buyer_sourcing_methods',
    value: '10 cash buyer sourcing methods ranked: (1) Zillow For Rent — call self-listers (not property managers). Script: "I\'m a wholesaler. Are you looking to buy more rentals? I just locked up a deal in your neighborhood." (2) Facebook groups — post + search tactic. (3) Cold calling cash sale list — XLeads → skip trace → call. "I saw you bought [address] for cash. Are you buying more?" ~25% say yes. (4) Local property auctions — 9 people lose every bid, still have cash. Approach losers immediately after. (5) Local REIAs — ego fests but real buyers attend. (6) Discord/community — JV with others who have buyers. (7) Hedge funds — still active, prefer higher price points. (8) REALTORS — Zach\'s best source. Pull buyer\'s agent from cash sale list. Call: "I lock up off-market deals regularly. I\'ll pay you far more than 3% MLS commission." Realtors have wealthy clients (surgeons, CEOs) who don\'t know wholesale exists. (9) Title companies — see every cash buyer who closes. Ask for referrals. (10) XLeads Investor Leads (pro/X plan) — pull top flippers and landlords by city/county, filter to 5-50+ flips/year. BUYER TIER SYSTEM (lowest to highest price they pay): 1=Slumlords (50+ houses/year), 2=High-level flippers (20+ flips), 3=Medium flippers (5-10 deals), 4=Mom-and-pop flippers, 5=Fresh seminar buyers (have capital, unfamiliar with discounts = pay closest to retail). Target tiers 4 and 5 for maximum assignment fees. Schedule: mornings = find buyers, afternoons/evenings = call sellers.'
  },
  {
    key: 're_cash_buyer_qualifier_5q',
    value: 'Zach\'s 5-question cash buyer qualifier before adding to buyers list: Q1: "Are you looking to buy more houses for flipping or renting?" If no = not active, do not add. Q2: "Have you bought from a wholesaler before?" No = yellow flag, needs education. Q3: "Are you okay with us making an assignment fee?" If uncomfortable with fees over $10K = drop immediately (will renegotiate at closing). Q4: "Give me your LLC name." Look up on county property appraiser — real active buyers have purchase history in their LLC name on public deeds. More reliable than proof of funds (easily faked). No history despite claiming experience = they lied. Q5: "What price range, property type, and areas do you buy in?" Cross-reference with actual purchase history. Store: flip/rent preference, target price range, preferred property types, desired areas, prior purchases, comfortable with assignment fees, preferred communication, buying timeline.'
  },
  {
    key: 're_cash_buyer_walkthrough_protocol',
    value: 'Complete cash buyer walkthrough protocol: BEFORE: Call buyer + pitch at MAO → email/text address and photos → follow up next day if no response → once buyer agrees on price, confirm: "Before I walk you through, I\'m only showing this to 1-2 people. If you see it and it matches the pictures, can you commit to sign the assignment contract and wire the deposit that same day?" If buyer hesitates = not committed, do not schedule. TELLING SELLER (do not ask permission): "Remember when we signed the agreement — I mentioned my partner and I would come by to look at repairs. My partner [name] and I are going to stop by Tuesday afternoon. When\'s a good time?" Frame as "partner" = normal business activity. DURING: NEVER let cash buyer talk to seller. Keep seller occupied in separate room. Cash buyer does visual inspection only. Cash buyer does NOT reveal purchase price to seller. AFTER: Sign assignment contract OUTSIDE or at coffee shop — never in front of seller. EARNEST MONEY: $3K-$5K non-refundable minimum. Non-negotiable. "A buyer falling through only means you did not have an EMD." If they forfeit: keep $4K, give $1K to seller to extend, find new buyer.'
  },
  {
    key: 're_title_company_framework',
    value: 'Rick Ginn\'s title company framework (23 years): Finding wholesaler-friendly companies: local REIAs, Facebook RE investor groups, Google with investor reviews. Prefer small boutique firms (close in 2-10 days) over national chains (minimum 30 days). Get ONE point of contact with personal cell. 3 SCREENING QUESTIONS (in order): Q1: "Do you work with real estate investors?" / "Do you specifically work with wholesalers?" If they hang up = move on. Q2: "Are you familiar with assignment of contract?" Some say it\'s illegal (it is not) — do not argue, just move on. Q3: "Can you send me a full disclosure of all your closing fees?" Must provide by law. Get this before doing any deals. FEE STRUCTURE — NON-NEGOTIABLE: documentary stamps, intangible taxes, recording fees, title insurance premium (FL: ~$575 on $100K). NEGOTIABLE: search fee ($100-200 reasonable, over $300 negotiate), lien search ($100-150), settlement/closing fee ($350-$1,500, never pay over $1,500). Total negotiable fees: $600-$2,000. CRITICAL RULE: Send signed PSA to title company IMMEDIATELY after signing — do NOT wait until you have a buyer. Title issues can take 30-90 days to cure. STRATEGIC USE: Title company calling your seller eliminates all "this is a scam" doubt from family members. Always use YOUR title company, never buyer\'s.'
  },
  {
    key: 're_virtual_wholesale_differences',
    value: 'Two critical differences for virtual (Memphis) wholesaling vs. in-person: (1) SPEED REPLACES RAPPORT — No appointment, no site visit. Give offer on same call when possible. Pre-fill DocuSign contract with seller name, address, and offer price before the call so you can send within 30 seconds of verbal acceptance. (2) STAY ON THE PHONE AFTER VERBAL ACCEPTANCE — #1 virtual wholesale mistake is hanging up after "yes." TRANSITIONAL STATEMENT: "Awesome. What I\'m going to do is send over the agreement right now. Let me stay on the phone and send it to your email. Just let me know when you get it." Stay on the phone until DocuSign is SIGNED. Why: if seller opens contract unsupervised and hits a clause they don\'t understand, no one answers → "this is a scam" → deal dead. GOOD COP/BAD COP script: "I was talking to my partner Rick. He\'s saying he can only do $140K. [Pause] I know, he\'s crazy. He always goes too low. That\'s why I\'m here with you. What price actually works for you?" BOOTS ON GROUND needed after signed contract for photos and buyer walkthrough.'
  },
  {
    key: 're_assignment_contract_critical_clauses',
    value: 'Rick Ginn\'s 5 most critical assignment contract clauses most wholesalers miss: Clause 7 — EXPIRATION BUFFER: Set assignee\'s closing date 7-10 days BEFORE your PSA expires. If buyer fails to fund, you still have time to find another buyer. Clause 8 — NON-REFUNDABLE DEPOSIT: $5,000 minimum, wired (not check) within 24 hours of signing. Sub-$1K deposits = buyers who walk. Clause 9 — NO SELLER CONTACT: If assignee contacts seller directly, deal is void and deposit is forfeited. Clause 12 — RENEGOTIATION CLAUSE (Rick\'s "$1M clause"): "If assigner renegotiates purchase price downward, the difference goes to the assigner as an additional assignment fee, not the assignee." Example: locked at $100K, buyer paying $120K, you renegotiate seller to $95K = that extra $5K is YOURS. Without this clause, buyers claim the savings. This clause alone has earned Rick over $1,000,000. Clause 13 — AS-IS: No warranty on condition, assignee accepts as-is. Additional: Always use YOUR title company. Give buyer PSA copy only AFTER they sign AND wire deposit. Any buyer who complains about your profit = drop immediately.'
  },
  {
    key: 're_repair_cost_grid',
    value: 'Three-tier repair cost estimation grid by square footage: Under 1,500 sqft: Light=$15K, Medium=$27K, Heavy/gut=$60K. 1,500-3,000 sqft: Light=$18K, Medium=$33K, Heavy=$65K. 3,000+ sqft: Light=$25K, Medium=$45K, Heavy=$75K. AI ESTIMATION METHOD: Use Zach\'s free AI repair guide (freewholesaling.com) → input sqft, roof needed, kitchen, flooring, bathrooms, foundation → generates ChatGPT prompt → paste → low/high range returned. PHOTO METHOD (most accurate for virtual): Take photos via boots-on-ground → upload to ChatGPT → "Estimate repair costs based on these photos." Currently 80-90% accurate. KEY RULE: Always err on high side. Underestimated repairs = deals that go upside down. Protect MAO calculation.'
  },
  {
    key: 're_marketing_volume_benchmarks',
    value: 'Contacts needed per deal by channel (Zach\'s real-world benchmarks): Regular DFD: 500 leads/deal. Reverse DFD (sticky notes): 400 leads/deal. Government lists (call or text): 2,000-3,000/deal. Paid lists (XLeads high equity): ~6,000/deal. Direct mail postcards: ~4,000/deal. Digital bandit signs (Facebook posts): ~500 posts/deal. Email blasting: ~60,000 emails/deal. PPL: $8-14K per deal cost (15-20 leads × $400-600, leads sold to 15+ other buyers simultaneously — Zach: "I don\'t personally know one person making $50K/year from PPL who doesn\'t also sell a PPL coaching program"). 16-channel marketing priority order: 1=Cold calling, 2=SMS text blasting, 3=Email blasting, 4=Reverse DFD, 5=Digital bandit signs, 6=DFD, 7=Door knocking, 8=Direct mail, 9=Referrals, 10=JVing, 11=Physical bandit signs, 12=SEO, 13=PPC ($7-8K/mo min), 14=Facebook ads, 15=Radio/TV, 16=PPL (AVOID entirely). List quality rank: 1=DFD (cannot buy), 2=Government lists, 3=Paid lists, 4=Public/MLS (avoid).'
  },
  {
    key: 're_weekly_activity_targets',
    value: 'Zach\'s minimum weekly activity targets (the floor, not ceiling): Calls/week=400, Texts/week=300, DFD leads/month=50+, Government list records/week=1,000, Probate records/month=100-500, Total contacts/week=750, Hours/week=25 minimum. Calling window: 4pm-6pm daily. Contact rate target: 20%+ answer rate. First-year goals (conservative): Month 1=1 deal ~$10K, Quarterly=3 deals ~$30K, Annual=12 deals ~$120K. FREE TECH STACK (zero budget): Dialer=Google Voice, SMS=6 Google Voice accounts (5/hr each=30/hr=300/day), Skip trace=TruePeopleSearch+CyberBackgroundChecks, CRM=free Google Sheets (Zach\'s template), E-sign=PandaDoc free, Lists=government only, Email=Gmail mail merge, Contracts=freewholesaling.com state-approved (free). Every wholesaler making $100K+/year uses paid lists. Minimum viable paid budget: $97/month (XLeads basic).'
  },
  {
    key: 're_psa_contract_rules',
    value: 'Rick Ginn\'s PSA rules: DEPOSIT: $250-$500 minimum (never $0 or $10). Frame to seller: "The deposit just opens escrow and gets title started. The real commitment is the $X I\'m handing you at closing." If seller demands over $1K deposit = red flag (bad motivation). CLOSING DATE: 30 days minimum for beginners, 60-90 preferred. Inspection period: NEVER match to closing date — set at 50% of closing window (30-day contract = 15-day inspection max). ASSIGNABILITY CLAUSE: Every contract must say "This contract is assignable by buyer." Only non-assignable if contract EXPLICITLY says so. LEGAL DESCRIPTION: Pull from county property appraiser or deed — exact copy. Can use parcel ID number in place of full legal. TAX PRORATION: If paying back taxes, specify max dollar cap: "Buyer agrees to pay 2024 property taxes not to exceed $3,000." Without cap = surprise $15K+ tax bill. EXIT STRATEGY: Notify seller verbally + text + email + certified mail. Reason to seller: "Unforeseen repair issues changed the numbers." Never admit you can\'t find a buyer. SEND TO TITLE COMPANY IMMEDIATELY after signing — do not wait for a buyer.'
  },
  {
    key: 're_llc_taxes_wholesale',
    value: 'Rick Ginn\'s LLC + tax framework for wholesalers (23 years): 3 steps 98% skip: Step 1=File Articles of Incorporation with state ($100-200). Step 2=Get EIN from IRS (free, instant). Step 3 (SKIPPED)=Designate entity classification with IRS within required deadline. Missing this = IRS defaults to suboptimal classification. Step 4 (ALSO SKIPPED)=Create Operating Agreement — private internal document (not filed with state). Banks require it to open business accounts. Without it, no real LLC structure. Common mistakes: Local CPA with no wholesaling experience treats you like W2 (maximum taxes, wrong classification). DIY QuickBooks without understanding balance sheets. CRITICAL TAX TOOLS: Section 199A = 20% income deduction for qualified business income (under $191,950 single / $383,900 joint). Car depreciation = vehicle used for DFD/appointments deductible. Pre-tax: travel/training/equipment/retreats with proper classification. 401K as business owner + HSA available. IRS brackets: 22-32% = active wholesaler income range. Without strategy a successful wholesaler loses $50K+/year. RECOMMENDED: wholesalingtax.com — LLC setup, entity classification, bookkeeping, personal + business returns unified. Designed specifically for wholesalers.'
  },
  {
    key: 're_skip_tracing_and_dnc',
    value: 'Skip tracing comparison: FREE (CyberBackgroundChecks, TruePeopleSearch): 50-70% accuracy, 60-70 hours per 1,000 records. Best for individual lookups, probate relative finds. PAID XLeads: 80-85% accuracy, under 5 minutes per 1,000 records. 15K traces/month included in $97 XLeads basic. Other paid options: $0.10-0.15/trace = $1,500 for 15K. PERSONAL SECURITY: CyberBackgroundChecks has your home address and all prior addresses publicly visible. Go to both sites and click "Remove my information." DNC EXEMPTION: Wholesalers are technically exempt from DNC because you are making a cash offer (not telemarketing a good/service) — TCPA exemption. Not legal advice, but Zach calls DNC numbers. Flag DNC on lists but do not auto-exclude — Brock decides. DFD VOICEMAIL HACK: While driving, open iPhone Voice Memos → record addresses aloud. iPhone auto-tags recordings with location. After drive: paste all recordings into ChatGPT → "Transcribe into spreadsheet format for driving for dollars tracking." Replaces manual data entry and prevents distracted driving.'
  },
  {
    key: 're_disposition_process',
    value: 'Complete deal disposition (selling) process: 4 STEPS: (1) Build buyers list in advance — do this in mornings before seller outreach begins. (2) Lock up a deal. (3) Call 3-5 qualified buyers privately — do NOT mass blast (signals desperation, tells every buyer you can\'t sell it). (4) Walk buyer through → assignment contract + EMD → close. FEE TRANSPARENCY TEST: Send deal at MAO price. Any buyer who objects to your assignment fee = DROP them immediately. Real buyers care about their own flip profit, not your cut. "If they can\'t handle a $20K fee on a deal where they make $50K, they aren\'t serious." CASH BUYER RULE: If buyer says "I just need my hard money lender\'s approval" = NOT a cash buyer. Hard money lenders can pull approval day of closing. Only accept: private money already in buyer\'s bank account. SELLER CONTACT SCRIPT for scheduling walkthrough: "Remember when we wrote up the agreement — I mentioned my partner and I would come take a look at repairs before closing. My partner [name] and I want to stop by [day]. What time works best?" Do NOT ask permission — state it as already planned, ask only for timing. JV OPTION: When you have no buyers, JV with community member who has buyers (frwholesaling.com map). 50/50 split on assignment fee.'
  }
];

client.connect().then(async () => {
  let inserted = 0;
  for (const m of memories) {
    try {
      await client.query(
        `INSERT INTO memories (user_id, key, value, source)
         VALUES ($1, $2, $3, $4)
         ON CONFLICT (user_id, key) DO UPDATE SET value = EXCLUDED.value, source = EXCLUDED.source`,
        [USER_ID, m.key, m.value, 'transcript_extraction_2026-05-28_batch3']
      );
      inserted++;
    } catch(e) {
      console.log('Failed:', m.key, '-', e.message.slice(0, 80));
    }
  }
  console.log('Done:', inserted + '/' + memories.length + ' memories inserted/updated');
  client.end();
}).catch(e => { console.error('Connection failed:', e.message); process.exit(1); });
