const { Client } = require('./node_modules/pg');
const client = new Client({
  host: 'kodama.proxy.rlwy.net', port: 55551,
  user: 'postgres', password: 'yBtFmogbIuHGfNhHFhzrmlhANWfgrzxC',
  database: 'railway', ssl: { rejectUnauthorized: false }
});

const memories = [
  { key: 're_conditioning_agreement_script', value: 'The conditioning statement is delivered BEFORE every seller appointment — both by phone AND in person. Exact script: "Mr. Seller, before I come see the house, I don\'t want to waste your time. I\'m going to take a look at the property, and when we\'re done, you\'ll have a decision to make: a definitive YES or a definitive NO. Can I get your commitment to give me that yes-or-no decision?" Zip your lip after asking. If they stall AFTER conditioning: "Remember before we met, we agreed to a yes-or-no decision. What information are you missing?" Deliver on initial phone call AND reinforce at start of appointment.' },
  { key: 're_seller_nonverbal_communication', value: '65% of a seller\'s decision is based on NON-VERBAL communication. Four pillars: (1) TONALITY — vary pitch, pace, enthusiasm; never be monotone. (2) SPEED — mirror seller\'s pace exactly. (3) POSTURE — always upright/confident; do NOT mirror poor posture. (4) WORD TIMING — after making a verbal offer, go COMPLETELY SILENT. Even 2 full minutes. If they counter and you want to accept, still pause for the same amount of time they took — they must feel they negotiated you down.' },
  { key: 're_followup_cadence_exact', value: 'Exact follow-up schedule: 0-30 days = daily contact. 30-60 days = weekly. 60-90 days = bi-weekly. 90-180 days = every 30 days. 180+ days = every 45 days. December uniquely powerful — year-end triggers decisions as people make New Year resolutions. 70% of deals come from follow-up, not first contact.' },
  { key: 're_double_closing_process', value: 'When assignment of contract is blocked, use double closing: two separate HUD closings same day. Legal in all states. Best funding: use cash buyer\'s own escrow funds (buyer signs consent directive, title company floats A-to-B first, then B-to-C immediately). No hard money required if buyer consents. Title company often discounts second closing 50%+. Minimum profit for double close: $10K+. If using hard money: focus on POINTS not interest rate, watch prepayment penalties.' },
  { key: 're_wholetailing_rules', value: 'Wholetailing = buy and sell slightly below retail within 90 days. Qualifies on less than 10% of deals. Requirements: high-demand property + cosmetic repairs only (no roof/foundation/electric) + minimum 2x assignment fee profit. 90-day rule is absolute. Buyer must be cash OR conventional with 20% down + waived appraisal contingency. No FHA. Repairs budget: max $10-20K. Price just below retail aggressively — one shot. Sell the vision after light cosmetic cleanup: pressure wash, dumpster, fresh paint, appliances.' },
  { key: 'saas_pricing_5_strategies', value: '5 SaaS pricing strategies: (1) Van Westendorp survey — reveals willingness-to-pay and feature value ranking. (2) Histogram feature analysis — move enterprise-only features to top tier, make mid-use features paid add-ons. (3) Tiered pricing (3+ tiers) — top tier is price anchor. (4) Value metrics — outcome-based scales infinitely. (5) Sawdust monetization — partner with adjacent vendors, keep 30-50% on referral with zero delivery cost.' },
  { key: 'saas_sales_pipeline_4roles', value: 'Full SaaS sales pipeline: (1) SDR — inbound qualifier, speed-to-lead critical, call within minutes of form fill. (2) BDR — outbound prospector. (3) AE — quota-carrying closer, use MEDDIC not BANT. (4) CSM — post-close activation, expansion revenue, churn prevention, handles $1-2M ARR per person. Hire order for founders: CSM first, then SDR, then AE.' },
  { key: 'saas_sales_3_questions', value: 'Every SaaS sale must answer 3 questions: (1) Why do ANYTHING? Give compelling why-now. (2) Why YOUR solution? Acknowledge alternatives and explain why you win. (3) Why NOW? Create urgency through consequence of inaction. For Valdr Ops: (1) You\'re losing $X/mo in missed calls right now. (2) Unlike DIY, our AI books appointments not just takes messages. (3) Every week you wait is another week of lost revenue.' },
  { key: 'saas_sales_3vc_bamfam', value: 'Shorten sales cycles: (1) Audit 3VC: Volume, Value, Velocity, Conversion — measure these 4 numbers first. (2) BAMFAM = Book A Meeting From A Meeting — never end a call without scheduling next one. (3) Multi-thread accounts: ask who was involved last time they bought software and reach out to those people. (4) Sell a paid POC ($10-25K pilot) to break long enterprise cycles down to 2-3 months.' },
  { key: 'saas_customer_value_extraction', value: 'Customer journey: Red (signed, not using) → Yellow (using, no habit) → Green (paying happily) → Purple (referring). Seed the referral in the ORIGINAL CONTRACT: "If we deliver these outcomes, you agree to refer 2 people like yourself." Ask sequence: written testimonial → podcast → video → ambassador referral → sales reference. BRAG IT UP: when customer wins, celebrate with them, get them reliving the moment, THEN make the ask.' },
  { key: 'saas_6functions_kpis', value: '6 SaaS KPIs by function: Product: North Star Metric + activation rate + NPS. Engineering: active defects + velocity + test coverage. Marketing: MQL count + CAC per channel. Sales: demos/week + win rate + new MRR. Customer Success: time-to-first-response + expansion MRR. Finance: eNPS + contribution margin. North Star = 1 number capturing both customer and business value simultaneously.' },
  { key: 'business_meeting_cadence_OS', value: 'Operating system meeting cadence: (1) Daily standup — 3 wins yesterday / 3 priorities today / blockers, max 30 sec/person. (2) Weekly sync — scorecard + quarterly rocks + issue resolution. (3) Monthly review — projects green/yellow/red status. (4) Quarterly planning — 90-day sprint. (5) Yearly strategic planning — 10-year target → 3-year vision → 1-year goals. All major pivots belong ONLY in annual planning.' },
  { key: 'business_replacement_ladder_detailed', value: 'Replacement Ladder to $1M: (1) Admin/assistant first. (2) Clone delivery — document onboarding so founder not required. (3) Automate lead gen — content → inbound → automated follow-up. (4) Delegate sales — the freedom step; as long as founder is on sales calls, business sleeps when founder sleeps. (5) Leadership hires — compensated with profit sharing so they behave like owners. Business model filter: must have 40%+ gross margin.' },
  { key: 'business_3_diagnostic_questions', value: '3 CEO diagnostic questions: (1) 10x test: If business grew 10x tomorrow, what breaks first? Invest there NOW. (2) New owner question: If someone bought my business, what is the FIRST thing they would change? (3) Hire-back question: If I laid everyone off, who would I enthusiastically rehire? People you hesitate on need a transition plan. Max 7 direct reports; first 7 hires should be people-managers not sole contributors.' },
  { key: 'business_onboarding_5steps', value: '5 steps to retain new hires: (1) Orientation — vision, values, accountability chart. (2) Program document — one master document per department; new hire reads every link before starting. (3) 90-day goals — clear picture of winning in first 3 months. (4) Buddy system — assign someone NOT their direct report; no friend in 2 weeks = high probability of leaving by 6 months. (5) Scheduled 1-on-1s — Day 1, Week 1, 2-week mark, then monthly.' },
  { key: 'business_50_fix_it_rule', value: 'Anyone in your organization has authority to solve any problem under $50 without asking — they report what they did afterward. Eliminates decision-log bottlenecks. For ODIN: if a problem can be resolved with less than $50 of cost or equivalent time value, ODIN should resolve autonomously and report in next briefing rather than interrupting for approval. Assumes trust established and agent knows organizational values and priorities.' },
  { key: 'mindset_maps_ai_framework', value: 'MAPS framework for AI prompts: M = Mission (outcome goal, not the task). A = Ask (one specific concrete request). P = Parameters (all context: ICP, what has worked, constraints — use VOICE input, speak 3x faster than typing). S = Shape (output format — CSV, markdown, bullets, length, tone). Rule of 3 Rs for automation: Repetitive (weekly+) + Rule-based (same I/O) + Return (saves more time than build cost).' },
  { key: 'mindset_sell_before_build', value: 'Default when you have an idea: find a paying STRANGER before building anything. A paying stranger = proof of PMF. FOCUS = Follow One Course Until Successful: one clear customer, one clear product, one clear marketing channel, one clear sales channel — all four locked for minimum one year before adding anything. Most wealth is destroyed by distraction, not failure. First question before any new build: Who is the first paying stranger and how will you find them?' },
  { key: 'mindset_model_before_modify', value: 'Execute any new system, script, or process EXACTLY as taught before modifying anything. Modification before traction = the reason most coaching clients fail — you remove the variable that was working without knowing which one it was. Apply to RE: use Rick/Zach scripts verbatim until 3+ deals closed. Apply to Valdr Ops: use the 3-question framework verbatim for 30 days before A/B testing. Before results = follow the model exactly.' },
  { key: 'mindset_patience_framework', value: 'Two separate time speeds: (1) PATIENT with the timeline (10 years is fine). (2) RUTHLESSLY IMPATIENT with daily activity. Apply to RE: measure success by cold calls made, texts sent, follow-ups completed TODAY — not deals closed. Most people quit after 2-4 months because they are impatient with the timeline and indifferent to daily action — exactly backwards.' },
  { key: 'mindset_energy_vs_time', value: 'You do not manage time — you manage energy. Structure calendar around energy type: Mornings = creative/strategic (biggest open problems). Afternoons = meetings and conversations. Went from 80-100hr/week low output to under 40hrs/week 40-50x output purely by managing energy not hours. For ODIN morning briefing: ask what is the big creative problem for today, not just the task list. 4 focused hours beats 12 distracted hours.' },
  { key: 'mindset_advice_quality_filter', value: 'Only 3 valid advice sources: (1) Mentors = people who have done exactly what you want to do. (2) Coaches = deep domain specialists with a blueprint for the specific skill. (3) Peers = people 1-2 years ahead of you on the same path. Everyone else: listen politely, ignore. Dan invested $1.7M in mentors and coaches over 27 years, considers it highest ROI investment, generating thousands of times more than S&P 500 on that capital.' },
  { key: 'finance_buyback_rate_formula', value: 'Buyback rate formula: Annual income divided by 2,000 hours divided by 4 = max hourly cost to outsource any task. At $100K income: $12.50/hr. At $200K: $25/hr. At $400K: $50/hr. Any task outsource-able for less than the buyback rate = immediate delegate. The divide-by-4 factor requires 4x ROI on buying back an hour. Wealthy people spend money to save time; broke people spend time to save money.' },
  { key: 'finance_cashflow_customer_financing', value: 'Do not finance your customers. Customers must pay upfront — using credit to fund delivery means you are bankrolling their operations. For Valdr Ops: offer annual pricing with 10-20% discount; 12 months revenue in bank on day 1 per client. For RE: require earnest money deposit from cash buyer before coming off market. Collect 50-100% upfront before starting work. Cash flow is the #1 cause of death for growing companies.' },
  { key: 'finance_gross_margin_filter', value: 'High gross margin is the #1 business model selection criterion. Below 40% gross margin = cannot reinvest fast enough to bootstrap; will require external capital. SaaS target: 40-50%+ operating margin. RE wholesaling: near-100% gross margin (no product cost, only time). Valdr Ops: high margin if not paying human labor for delivery. First question for any new opportunity: What is the gross margin? If below 40%, scaling is painful without capital injection.' }
];

client.connect().then(async () => {
  let inserted = 0;
  for (const m of memories) {
    try {
      await client.query(
        `INSERT INTO memories (user_id, key, value, source)
         VALUES ('a4ede2f8-b3b1-4158-816f-e7503dab81a4', $1, $2, $3)
         ON CONFLICT (user_id, key) DO UPDATE SET value = EXCLUDED.value, source = EXCLUDED.source`,
        [m.key, m.value, 'transcript_extraction_2026-05-28_batch2']
      );
      inserted++;
    } catch(e) {
      console.log('Failed:', m.key, '-', e.message.slice(0, 80));
    }
  }
  console.log('Done:', inserted + '/' + memories.length + ' memories inserted/updated');
  client.end();
}).catch(e => { console.error('Connection failed:', e.message); process.exit(1); });
