const { Client } = require('./node_modules/pg');
const client = new Client({
  host: 'kodama.proxy.rlwy.net', port: 55551,
  user: 'postgres', password: 'yBtFmogbIuHGfNhHFhzrmlhANWfgrzxC',
  database: 'railway', ssl: { rejectUnauthorized: false }
});

const USER_ID = 'a4ede2f8-b3b1-4158-816f-e7503dab81a4';

const memories = [

  // ─── NEW BUSINESS IDEAS / INCOME STREAMS ────────────────────────────────
  {
    key: 'biz_idea_8_high_income_businesses_2026',
    value: 'Dan Martell\'s 8 best businesses to start in 2026 ranked by gross margin: (1) Chat Sales Agency (40-50% margin) — manage DM/chat conversations for influencers with large audiences who never talk to followers. Tool: Revio CRM to manage all social chat channels + AI summaries. (2) Personal Brand Agency (40-50% margin) — grow personal brands, charge retainer + performance upside on follower/revenue growth. Cut clients who lack the "it factor" fast. (3) Ghost Writing Agency (50-60% margin) — write books and content in client\'s voice. Charge 50%+ upfront. Speak at events where book-writers gather (entrepreneurs, executives). Dominate one niche. (4) VA Placement Agency (50-60% margin) — match businesses with virtual assistants. Charge on delivery (not upfront). Offer 2-month replacement guarantee at no fee = Viral Word of Mouth. Send Dan\'s "Buy Back Your Time" book to fence-sitters. (5) VR Training Agency (60-70% margin) — sell VR training to enterprises (surgery, flight, high-stakes). Sell enterprise packages only (not SMB). Add ongoing subscription for support. Finance the hardware (buy wholesale, sell retail + configuration fee). (6) Gamified Learning Platform (60-70% margin) — target high-turnover companies (car dealerships, insurance, retail, QSRs). Use white-label platforms like membership.io. Freemium community entry converts to paid membership. (7) AI Automation Agency (70-80% margin) — help businesses implement AI. Start by consulting on tools before building automations. Automate what makes client money FIRST. Build partnerships with people who already have your ideal client audience. (8) AI-First SaaS (80-90% margin) — "Success as a Service" (SaaS no longer means Software as a Service). Build AI that delivers outcomes via chat/voice with no traditional UI. Dan\'s personal all-in focus. Pick boring industries (Legal, Medical, Building, Manufacturing) — least competitive. Pre-sell before building anything.'
  },
  {
    key: 'biz_idea_ai_income_skills_ranked',
    value: 'Dan Martell\'s 9 AI skills ranked by hourly income potential (2026): (1) Prompt Engineering: $50-100/hr. Structure: Role → Data → Ask → Format. (2) AI-Assisted Software Development: $100-200/hr. Use Cursor, Replit, Retool — non-technical people building apps with AI. (3) AI Design: $100-200/hr. Generative photo (Midjourney), photo editing (Photoshop AI, Topaz), web design (Figma + AI, Reloom.io). (4) AI Video Editing: $100-200/hr. Three skills: Clipping (Firecut, Opus), Generative Video (Vidyard AI avatar, Synthesia), B-roll search + AI generation. (5) AI Writing: $100-200/hr. Three skills: Extraction (pull gold from transcripts), Ideation (feed best-performing content → generate new angles), Creation (build custom GPT in client\'s exact voice). (6) AI Content Marketing: $200-300/hr. Build the full content machine for a client — podcast + newsletter + social clips + app, all AI-run. Example: Arnold Schwarzenegger\'s Pump Club podcast, newsletter, and app is entirely run by an agency using AI. Arnold has never recorded a podcast. (7) No-Code AI Automation: $300-400/hr. Map workflow → automate cash-generating steps first → build AI co-pilots sitting next to workers. Tools: Make.com, N8N, Zapier, Gum Loop. (8) AI Data Analysis: $300-400/hr. Data cleanup (consolidate messy spreadsheets), data enrichment (append contact/location/credit data using 6sense, FullStory), data insight extraction (find patterns like Lomi found which US states buy most). (9) No-Code AI Agent Development: $400-500/hr (HIGHEST). Build agents that replace employees 24/7. Three steps: Define the job → Develop the model with training data → Deploy + monitor + thumbs up/down feedback loop to improve.'
  },
  {
    key: 'biz_idea_1person_ai_business_framework',
    value: 'Dan Martell\'s 7-step framework to build a $10M+ one-person AI business: (1) FIND PAINFUL PROBLEM — "Must-have" not "nice to have." Vitamins vs painkillers. Call 10+ people in a niche, ask for advice not a sale. "If you call for advice you get a sale, if you call to sell you get advice." (2) SOLVE MANUALLY FIRST — Get paid to learn the workflow before automating. Build a one-page done-for-you offer: Problem + Promise + Timeline + Price + Guarantee. Example: "Stop losing customers. We\'ll clean your database and give insights in 30 days for $2,500/mo, or your money back." (3) BUILD CLICKABLE PROTOTYPE — Use Figma, UXpilot.ai, or Visily.ai. Can be photo-realistic and look 100% real. Test with 5 customers and record reactions. "Prototype not product." (4) VALIDATE WITH CASH — Do not build until strangers pay. Launch Early Adopter Program (Founding 50): offer 50% off annual price + VIP onboarding + road map influence. Pre-sell like Dubai real estate sells units off-plan before construction. (5) BUILD MVP — Core features only. If it doesn\'t impact 80%+ of users, put it on a list. Use Manus.ai: describe idea in plain English → it recommends tools and generates system prompts → paste into Lovable.dev → app builds itself in real time. (6) COLLECT FEEDBACK — Watch what they DO, not what they SAY. Set up weekly customer advisory board calls. Categorize feedback by feature area. Build feature priority matrix: Y-axis = how many customers use it, X-axis = how much they\'d pay for it. Invest only in top-right quadrant. Record all calls, feed to AI for analysis. (7) SCALE WITH AI AGENTS NOT HEADCOUNT — 0-$100K: do everything yourself using AI tools. $100K-$1M: build automations AI can run (onboarding, support, ops). $1M-$10M: stack AI agents, loop yourself in only for exceptions. "The days of bragging about team size are gone. Now it\'s how much revenue with the fewest people."'
  },
  {
    key: 'biz_idea_boring_industries_for_ai',
    value: 'Dan Martell\'s 5 best "boring" industries for AI disruption in 2026 (least competitive, highest need): (1) Supply Chain — logistics, route optimization, delivery forecasting. Everything bought via app creates massive backend AI need. (2) Admin — billing, scheduling, filing, sorting. AI reading from CRMs and Dropboxes to do admin work. (3) Home Services — roofing, HVAC, plumbing. Every truck-roll has a complex process. AI automation for dispatch, scheduling, follow-up = trillion-dollar combined market. (4) Legal Services — contract analysis, draft creation, due diligence questions. First thing people use AI for. Build workflow and structure into legal processes. (5) Team Training / Company AI — AI that joins every Zoom call, knows all SOPs, answers onboarding questions in real time. Every company will have a "company AI" — the person who builds it gets paid. KEY RULE: "Being too early and too technology-advanced is just as wrong as being too late." Focus on what\'s TRUE not what\'s NEW. The boring industries are where the money is. Avoid: marketing tech, consumer apps (too competitive, everyone\'s building there).'
  },
  {
    key: 'biz_growth_offer_structure_5parts',
    value: 'Dan Martell\'s 5-part done-for-you offer structure that closes million-dollar deals: (1) PROBLEM — State the pain in their exact language from validation calls. (2) PROMISE — The specific transformation/outcome they receive. (3) TIMELINE — How fast you deliver it. (4) PRICE — Called "the investment" (never "cost"). (5) GUARANTEE — What you\'re willing to commit to. Example: "Replace a full-time receptionist, end missed opportunities, and turn every ad click into a booked call with Your Atlas in 30 days for just $2,500/month." Cash flow structuring: (A) ANCHOR PRICING — Top tier is 3-5x more expensive than second tier to make middle tier look cheap. (B) SCARCITY — "Only a few spots" requires deposit today to lock in. (C) BONUS — Give the solution to the NEXT problem they\'ll have after you solve the first one. Make the bonus more valuable than the initial offer. (D) VOLUME PRICING — Multi-year or multi-seat discount to pull large cash upfront. Never call it a "discount" — call it "volume pricing." Revenue is vanity, profit is sanity, cash flow is vitality.'
  },
  {
    key: 'biz_growth_pixel_swap_growth_hack',
    value: 'Dan Martell\'s 3 AI business growth hacks that most people don\'t know: (1) DISTRIBUTION PARTNERS — Partner with someone who already has your ideal customer in their audience. Pay 10-20% referral fee. Offer to train their community for free as the entry point. Work with people who have events, webinars, YouTube channels, books. (2) PIXEL SWAP — Find a non-competing company that sells to the same customer. Swap Facebook pixels: you put their pixel on your site, they put yours on theirs. Now you can run hyper-targeted ads to each other\'s website visitors. This is the most effective ad spend possible because the visitor is already proven interested. (3) INSERT INTO EXISTING TOOLKIT — Build integrations or add-ons to bigger platforms (Zapier, Make, HubSpot, Slack, Notion, GoHighLevel, Shopify). Get listed in their marketplace. Get featured on their annual event. Facebook growth hack: bought address-book-import tools to send "you\'ve been tagged" emails to non-Facebook users → forced account creation → how they activated entire countries. Airbnb growth hack: built custom tool to publish Airbnb listings to Craigslist → tapped Craigslist\'s existing audience for free. RULE: "It\'s not a growth hack if everybody knows it." Find distribution that others don\'t.'
  },
  {
    key: 'biz_idea_founding_50_eap',
    value: 'Early Adopter Program (EAP) / "Founding 50" — Dan Martell\'s pre-sell framework: Before building anything, sell to 10-50 early customers at 50% off the annual retail price. Example: $100/month software = $1,200/year retail → charge $600 for Founding 50. Extras to include: VIP onboarding, implementation calls, ability to influence product roadmap, name on the "About" page. Framing: "I\'m looking for 10-50 early customers to come in and help shape the product. These are the folks who get early access to innovation that their competitors don\'t have yet." Why it works: early adopters WANT to co-create. They\'re not just buying software, they\'re buying a stake in the outcome. Their cash funds your development. Their feedback makes the product right. When you launch a new feature they suggested, DM them personally — "Because of your feedback, we built this." They become raving fans. Dubai real estate comparison: 70% of Dubai\'s billion-dollar buildings were pre-sold as off-plan units before construction began. Same principle. Rule: "Until people pay, they ain\'t going to pay attention. And if they ain\'t paying, their feedback is invalidated."'
  },
  {
    key: 'biz_idea_ai_content_marketing_agency',
    value: 'AI Content Marketing Agency model ($200-300/hr income potential): Build the full automated content machine for a client. Example — Arnold Schwarzenegger\'s Pump Club: top podcast, newsletter, and app. Arnold has never recorded a podcast. An agency manages everything using AI voice cloning, AI-written newsletter content, auto-publishing, and clip repurposing. Arnold just exists as the brand. You can replicate this for any expert or executive. Four steps: (1) DEFINE OUTCOME — Full strategy: podcast, newsletter, social clips, premium app, or combination. (2) CREATE CONTENT — Stack all AI skills: AI writing, AI video editing, AI design. One hour of content becomes 20+ pieces. (3) REPURPOSE — One long-form interview generates short clips, newsletter, tweets, LinkedIn posts, YouTube shorts — all AI-automated. (4) MAKE CLIENT OMNIPRESENT — They appear everywhere in their industry. They give you all the credit, refer you to peers. Pro tip: Podcast = access to anyone. Use a podcast as "flattery marketing" to get meetings with ideal clients who then become customers. "Not who you know anymore — it\'s who knows you."'
  },
  {
    key: 'biz_idea_success_as_a_service',
    value: '"Success as a Service" — Dan Martell\'s thesis on the future of SaaS: Traditional SaaS (Software as a Service) is dying. Businesses don\'t want software, workflows, and data entry. They want to press a button and get an outcome. The future = AI that monitors, acts, and delivers results without any human interaction. Dan calls it "Success as a Service." Examples: not a CRM where you manage customer data, but an AI that tells you what to do next with each customer. Not a scheduling tool, but an AI that automatically schedules based on context. Dan\'s Martell Ventures AI portfolio companies: (1) youratlas.com — AI replaces receptionist, books sales meetings, turns every ad click into a booked call. $2,500/month. (2) Social Sweep — AI analyzes all social networks, adds enrichment, lets you search and find anyone with specific knowledge across all platforms. (3) Precision — AI-powered business dashboard that monitors your data and tells you exactly what to fix to improve your numbers. KEY INSIGHT: Interface is dying. Future products are phone-driven or voice-driven with no UI. "The days of having a front-end app where people enter information are going away." Build AI that works in the background — they call a number, speak, magic happens. Opportunity window: 18-36 months to build something meaningful before space gets crowded.'
  },
  {
    key: 'biz_idea_no_code_ai_tools',
    value: 'No-code AI tools for building products without programming (Dan Martell validated list 2026): PROTOTYPING: Figma.com, UXpilot.ai, Visily.ai — describe product in plain English, get photo-realistic clickable mockups. BUILDING: Manus.ai — describe idea, it recommends tools AND generates system prompts. Lovable.dev — paste Manus prompts, watch the full app build in real time (minutes not months). Replit, Bolt.new, Cursor — AI-powered coding environments for non-technical founders. AUTOMATION: Gum Loop — Dan\'s favorite, AI-powered workflow automation. Make.com, N8N, Zapier — standard automation. GoHighLevel — CRM + marketing automation (same platform as XLeads Ninja Mode). CHAT/SALES: Revio — manages all social media channels + AI chat summaries + CRM for chat sales agencies. CONTENT: Fathom — AI meeting notes. Opus, Firecut — AI video clipping. Synthesia, Vidyard — AI avatar video generation. Reloom.io — builds entire websites from a prompt. RESEARCH: Manus AI — conducts research, analyzes markets, builds app specs from plain English. Process: Manus (plan) → Lovable (build) → Gum Loop (automate) = full AI app without writing a line of code.'
  },

  // ─── PERSONAL GROWTH / HIGH INCOME SKILLS ───────────────────────────────
  {
    key: 'mindset_7_high_income_skills',
    value: 'Dan Martell\'s 7 high-income skills that create unlimited wealth: (1) CONNECTING — Remember names (most beautiful sound to a human is their own name). Ask "how" and "what" questions to get stories. Follow up consistently. Get in bigger rooms (if you\'re the smartest, find a new room). If no room exists, create one (host an event around one speaker everyone wants to hear). (2) BEING LAZY — Systemize everything repeatable. "DRY = Do Not Repeat Yourself." Delegate everything someone else can do for less than your buyback rate. Set up sensors (reports/surveys) so delegated work doesn\'t go rogue. "Broke people get good at doing tasks. Rich people get good at avoiding them." (3) CREATING — Start content now, not when ready. Put your hand up to speak at every opportunity. Talk to your camera — it forces self-confrontation. Coach and teach weekly — reinforces your own learning and creates content simultaneously. "It\'s not who you know, it\'s who knows you." (4) SELLING — "Nothing happens in business until someone sells something." Selling = getting people to change a perspective. Income is directly related to ability to sell. Best salespeople talk the least — ask powerful questions that get the buyer to sell themselves. (5) LEADING — "Leaders know the way, show the way, go the way." Don\'t be transactional (tell → check → tell). Be transformational: clear outcome + measurement + coaching framework. (6) GRIT — "It\'s impossible to lose if you don\'t quit." Business is a game of WILL not skill. Overnight success takes years. Pain is not optional. Suffering is. The difference is having purpose for the pain. (7) VISION — "Any idea less than a billion-dollar opportunity isn\'t worth pursuing." The person aiming for $10M makes different decisions than the person aiming for $1M — same effort, completely different results. Write goals down, review 3-4x per day, SPEAK your vision publicly to activate it.'
  },
  {
    key: 'mindset_ai_era_3_skills_to_survive',
    value: 'Dan Martell\'s 3 skills that separate winners from losers in the AI era: (1) VISION — Directors (people who set direction) not doers. The AI revolution makes doers obsolete. Build 2-person teams with $10M revenue targets, where AI is the "doing" layer. (2) TASTE — Curation ability. Everyone has access to AI output. The person with taste knows what\'s good, what\'s valuable, what to build. Taste cannot be automated. (3) CARE — Genuine investment in customers, team, community. AI doesn\'t care. You do. This is the defensibility moat. ADDITIONAL RULES for the AI era: Presell everything before building. Establish a personal brand as your #1 defensibility moat (your business can be copied, but your brand cannot). The AI era rewards directors and penalizes executors. "In the future, companies won\'t brag about team size — they\'ll brag about revenue per person." Two-person companies with $10M revenue are the new benchmark. Use AI to automate 90-92% of work. Adopt AI tools NOW or get disrupted in 18-24 months.'
  }
];

client.connect().then(async () => {
  let inserted = 0;
  for (const m of memories) {
    try {
      await client.query(
        `INSERT INTO memories (user_id, key, value, source)
         VALUES ($1, $2, $3, $4)
         ON CONFLICT (user_id, key) DO UPDATE SET value = EXCLUDED.value, source = EXCLUDED.source`,
        [USER_ID, m.key, m.value, 'transcripts_batch5_2026-05-28']
      );
      inserted++;
    } catch(e) {
      console.log('Failed:', m.key, '-', e.message.slice(0, 80));
    }
  }
  console.log('Done:', inserted + '/' + memories.length + ' memories inserted/updated');
  client.end();
}).catch(e => { console.error('Connection failed:', e.message); process.exit(1); });
